# Generated by Django 4.2.4 on 2023-09-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='reco_marketing_promocional',
            new_name='preco_marketing_promocional',
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
